### ISSUE TITLE
[GUI][Bug] "All" and "Date desc" disappear when being clicked multiple times

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1172]
Visual bug, unable to open dropdown menu while clicking on text, related to #1081, although this bug wasn't appearing on 4.0 segregated testnet if I remember well.

![check](https://user-images.githubusercontent.com/57232689/70198267-ae54de80-170e-11ea-93fc-9f65cf3e3ce9.JPG)

**Comment by NoobieDev12** [comment]
Happens only on Windows Server 2016. Not happening on Windows 10 Pro.

**Comment by furszy** [comment]
This is most likely solved with #2173, give it another try on latest master or 5.1 branch and let me know.

**Comment by NoobieDev12** [comment]
Issue is still there. Tried with 5.1.0rc2 on mainnet on Windows Server 2019, didn't test on other OSs yet, but I guess it's the same.

**Comment by furszy** [comment]
@NoobieDev12 , check #2401 please.
